services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: todolist_db
      MYSQL_USER: todo_user
      MYSQL_PASSWORD: todo_password
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - todo-network

  app:
    build: .
    container_name: todo-app
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    networks:
      - todo-network

networks:
  todo-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local
